### ISSUE TITLE
Trained weights

### ISSUE THREAD

**Issue by ofirkris** [Ruifeng-Zhou24/AdaMatting#1]
Hello, thanks for sharing this implementation.
I'm learning about matting and am interested to test with the weights you've tested on, can you kindly share them here?

**Comment by Ruifeng-Zhou24** [comment]
hi, 
Thanks for your attention. This project is not finished yet and I am still working on the implementation. After it is fully implemented, i will share the trained model.

**Comment by leijue222** [comment]
Thanks for your work, hope you can provide more detailed in README and share  the trained model.Thanks!

**Comment by InternetMaster1** [comment]
Any updates?

Thank you
