### ISSUE TITLE
Pending implementation details

### ISSUE THREAD

**Issue by karnabhc** [Ruifeng-Zhou24/AdaMatting#2]
Hi,
May I know what are the pending work left to be done in this project?So that I can go ahead and implement the same and may be help you too if its within my abilities.
Thank You

**Comment by MarcoForte** [comment]
I would like to help complete this project also

**Comment by Ruifeng-Zhou24** [comment]
hi, 
thanks for your attention to this implementation. most part of this repo is finished now (except for the testing), and training should run just fine following the README
